export const REQUEST_SESSION_START = "REQUEST_SESSION_START";
export const REQUEST_SESSION_SUCCESS = "REQUEST_SESSION_SUCCESS";
export const REQUEST_SESSION_FAIL = "REQUEST_SESSION_FAIL";

export const REQUEST_DELETE_SESSION_START = "REQUEST_DELETE_SESSION_START";
export const REQUEST_DELETE_SESSION_SUCCESS = "REQUEST_DELETE_SESSION_SUCCESS";
export const REQUEST_DELETE_SESSION_FAIL = "REQUEST_DELETE_SESSION_FAIL";

export const SESSION_CREATED = "SESSION_CREATED";
